version: "3.3"
services:
    jenkins:
        image: jenkins/jenkins:lts
        user: root
        volumes:
            - /home/nika/:/var/jenkins_home
        ports:
            - '8080:8080'
            - '50000:50000'
    web:
        depends_on:
         - jenkins
        user: root
        image: tomcat:9.0
        volumes:
            - /home/nika/dockjen:/usr/local/tomcat/webapps/
        ports: 
           - '8888:8080'
        command: ["catalina.sh", "run"]
